Added a comment to test the docker build step in the GitHub Actions

diff --git a/.github/workflows/test_components.yaml b/.github/workflows/test_components.yaml
--- a/.github/workflows/test_components.yaml
+++ b/.github/workflows/test_components.yaml
@@ -54,3 +54,73 @@ jobs:
       - name: Run tests
         run: |
           pytest tests/
+
+  get-project-version:
+    runs-on: ubuntu-latest
+    outputs:
+        project_version: ${{ steps.project-version.outputs.project_version }}
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: Extract package version from pyproject.toml
+        id: project-version
+        run: |
+          project_version=$(./run.sh get_project_version)
+          echo "project_version=$project_version" >> $GITHUB_OUTPUT
+          echo "Project version: $project_version"
+
+  build-docker-image-and-push-to-registry:
+    runs-on: ubuntu-latest
+    needs:
+      - test-components
+      - get-project-version
+    defaults:
+      run:
+        working-directory: ./mlops-platform
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Login to Docker Hub
+        uses: docker/login-action@v3
+        with:
+          username: ciaa
+          password: ${{ secrets.DOCKER_HUB_TOKEN }}
+
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v3
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+
+      - name: Run build check
+        run: |
+          # This validates the Dockerfile and the build configuration
+          docker buildx build --check .
+
+      - name: Local image smoke test (build & create container)
+        run: |
+          IMG_TAG_TEST="ciaa/mlops-comps:${{ needs.get-project-version.outputs.project_version }}-test"
+
+          # Build locally (loads the single-platform build result to docker images)
+          echo "Build test image"
+          docker buildx build --platform linux/amd64 --load --tag "$IMG_TAG_TEST" .
+
+          SMOKE_CMD="import sys; print('ok'); sys.exit(0)"
+
+          echo "Run smoke command"
+          docker run --rm --entrypoint python "$IMG_TAG_TEST" \
+           -c "$SMOKE_CMD" || {
+              echo "Smoke test FAILED for $IMG_TAG_TEST"
+              exit 1
+          }
+
+          echo "Smoke test PASSED for $IMG_TAG_TEST"
+      - name: Build and push
+        run: |
+          IMG_TAG="ciaa/mlops-comps:${{ needs.get-project-version.outputs.project_version }}"
+          # Build and push the image to Docker Hub
+          docker buildx build --platform linux/amd64 --attest=type=provenance,mode=max --attest=type=sbom --tag "$IMG_TAG" --push .
